---
title: "Protocol of Preparing Course Material for LBGFS 2024"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Protocol of Preparing Course Material for LBGFS 2024}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Disclaimer
This documents the creation of the material of the course lbgfs2024.


# Protocol

```bash
cd ~/Data/Projects/Github/charlotte-ngs/
qrspm create lbgfs2024
cd lbgfs2024
# create subdirectories
for d in bash course_notes exercises website;do
  echo " * Create directory:  $d ..."
  mkdir -p inst/$d
  sleep 2
done
mkdir -p docs
```

Create quarto-projects for each of the different material categories

* website

```bash
cd inst/website
quarto create project website lbgfs2024 --no-open 
```

Copy the already existing material

```bash
cd lbgfs2024
cp ../../../../lbgfs2024_proj_root/website/lbgfs2024/*.qmd .
mkdir bash
cp ../../../../lbgfs2024_proj_root/website/lbgfs2024/*.sh bash
```

Test rendering website

```bash
./bash/quarto_render.sh
```

After refactoring, the website is rendered using 

```bash
./inst/website/lbgfs2024/bash/quarto_render.sh -z
```

Pages for exercises and solutions are added

```bash
# exercises
EXPATH=inst/website/lbgfs2024/exercises.qmd
echo '---' > $EXPATH
echo 'title: "Exercises"' >> $EXPATH
echo '---' >> $EXPATH
echo >> $EXPATH
echo >> $EXPATH
echo '```{r}' >> $EXPATH
echo '#| echo: false' >> $EXPATH
echo '#| results: asis' >> $EXPATH
echo 'if (is.element("rmdhelp", installed.packages()))' >> $EXPATH
echo '  cat(paste0(rmdhelp::get_latest_change()))' >> $EXPATH
echo '```' >> $EXPATH
echo >> $EXPATH

# solutions
SOLPATH=inst/website/lbgfs2024/solutions.qmd
echo '---' > $SOLPATH
echo 'title: "Solutions"' >> $SOLPATH
echo '---' >> $SOLPATH
echo >> $SOLPATH
echo >> $SOLPATH
echo '```{r}' >> $SOLPATH
echo '#| echo: false' >> $SOLPATH
echo '#| results: asis' >> $SOLPATH
echo 'if (is.element("rmdhelp", installed.packages()))' >> $SOLPATH
echo '  cat(paste0(rmdhelp::get_latest_change()))' >> $SOLPATH
echo '```' >> $SOLPATH
echo >> $SOLPATH
```

* course notes

```bash
cd inst/course_notes
quarto create project book lbgfs2024 --no-open 
```

Conversion of un-numbered titles

```r
convert_rmd_to_qmd("inst/course_notes/lbgfs2024/index_raw.qmd", "inst/course_notes/lbgfs2024/index.qmd")
```

Go back to the Rmarkdown version of the course notes.

```bash
cd ~/Data/Projects/Github/charlotte-ngs/lbgfs2024
cp -r ../lbgfs2023_gh-root/main/lbgfs2023/cn inst/
mv 03_gen_eval.Rmd 04-blup.Rmd 05-gencov.Rmd 06-variance-inbreeding.Rmd 07-add-asp-blup.Rmd 08-genomic-selection.Rmd attic/

```

## Setting Up New Repo
If changes to be pushed to Github get too big, the push does not work. Hence, smaller pieces are pushed. This leads to the requiredment of re-building the repo from a given state.

```bash
cd ..
mv lbgfs2024 lbgfs2024.bck.$(date +"%Y%m%d%H%M%S")
git clone https://github.com/charlotte-ngs/lbgfs2024.git
cd lbgfs2024
cp ../../../lbgfs2024.bck.20240918072153/inst/cn/*.Rmd .
rm A3_decomp_num_rel_mat.Rmd 
cp ../../../lbgfs2024.bck.20240918072153/inst/cn/*.yml .
cp ../../../lbgfs2024.bck.20240918072153/inst/cn/*.tex .
cp ../../../lbgfs2024.bck.20240918072153/inst/cn/*.css .
cp ../../../lbgfs2024.bck.20240918072153/inst/cn/*.bib .
```

Migrate figures in odg as they are needed

```bash
cd inst/cn
mkdir odg
for f in $(grep 'knitr::include_graphics' *.Rmd | cut -d '"' -f2 | cut -d '.' -f1 | sed -e "s|odg/||");do
  echo " * Figure: $f ..."
  cp ../../../lbgfs2024.bck.20240918072153/inst/cn/odg/$f.* odg
  sleep 2
  git add .
  git commit -m"Migrated figure $f"
  git push origin main
  sleep 2
done
```


## Slides
The slides are produced in a separate subdirectory

```bash
cd ~/Data/Projects/Github/charlotte-ngs/lbgfs2024
mkdir -p inst/slides/
cp -r ../lbgfs2023_gh-root/main/lbgfs2023/sl/l01_intro_lbg/ inst/slides/

# each odg separately
mkdir -p inst/slides/l01_intro_lbg/odg
for f in $(ls -1 ../lbgfs2023_gh-root/main/lbgfs2023/sl/l01_intro_lbg/odg/*.odg);do
  echo " * copy $f ..."
  cp $f inst/slides/l01_intro_lbg/odg
  git add .
  git commit -m"Migration of $f ..."
  git push origin main
  sleep 2
done
```


Deploy slides

```bash
mkdir -p inst/website/lbgfs2024/slides
# slides qmd
SLIPATHQMD=inst/website/lbgfs2024/slides/slides.qmd
echo '---' > $SLIPATHQMD
echo 'title: "Slides"' >> $SLIPATHQMD
echo '---' >> $SLIPATHQMD
echo >> $SLIPATHQMD
echo >> $SLIPATHQMD
echo '```{r}' >> $SLIPATHQMD
echo '#| echo: false' >> $SLIPATHQMD
echo '#| results: asis' >> $SLIPATHQMD
echo 'if (is.element("rmdhelp", installed.packages()))' >> $SLIPATHQMD
echo '  cat(paste0(rmdhelp::get_latest_change()))' >> $SLIPATHQMD
echo '```' >> $SLIPATHQMD
echo >> $SLIPATHQMD

# table data
SLIPATHDAT=inst/website/lbgfs2024/slides/slides.dat
echo 'Date;Text;Filename' > $SLIPATHDAT
echo '2024-09-20;Introduction;l01_intro_lbg.pdf' >> $SLIPATHDAT


```

Web dir

```bash
mkdir -p docs/slides
mv inst/slides/l01_intro_lbg/l01_intro_lbg.pdf docs/slides/
```


Migration of l02

```bash
mkdir -p inst/slides/l02_basics_qg
cp ../lbgfs2023_gh-root/main/lbgfs2023/sl/l02_qg_basics/lbgfs2023_slides_l02_basics_qg.Rmd inst/slides/l02_basics_qg/l02_basics_qg.Rmd

```
