project:
  type: website
website:
  title: LBG - FS 2024 | 0.0.4
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: course_notes.qmd
      text: Course Notes
    - href: weekly_news.qmd
      text: Weekly News
    - href: about.qmd
      text: About
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
