project:
  type: website
website:
  title: LBG - FS 2024 | 0.1.7
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: course_notes/course_notes.qmd
      text: Course Notes
    - href: exercises.qmd
      text: Exercises
    - href: solutions.qmd
      text: Solutions
    - href: slides/slides.qmd
      text: Slides
    - href: weekly_news.qmd
      text: Weekly News
    - href: about.qmd
      text: About
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
