# Week 12 
## lbgfs2024 0.12.0

* OHP: ohp_l09

# Week 11 
## lbgfs2024 0.11.6

Material for week 11:

* [Slides l11_gensel](https://charlotte-ngs.github.io/lbgfs2024/slides/l11_geno_sel.pdf)
* [Course Notes 07_gen_sel](https://charlotte-ngs.github.io/lbgfs2024/course_notes/07_gen_sel.pdf)
* [Exercise lbg_ex09](https://charlotte-ngs.github.io/lbgfs2024/exercises/lbg_ex09/lbg_ex09.html)
* [Correction ohp_l07](https://drive.google.com/file/d/1-_Qr0xjS3JxRYWC9BGEeahqKXXWvswsY/view?usp=sharing)
* [Correction l08_ainv](https://charlotte-ngs.github.io/lbgfs2024/slides/l08_ainv.pdf)
* [Solution lbg_ex07](https://charlotte-ngs.github.io/lbgfs2024/solutions/lbg_sol07/lbg_sol07.html)
* [OHP ohp_l08](https://drive.google.com/file/d/1-RUMotCCUZjk10xGtsb1S3uouAvs32IU/view?usp=sharing)

## lbgfs2024 0.11.5

* Slides l11_gensel

## lbgfs2024 0.11.4

* Course notes chapter 7

## lbgfs2024 0.11.3

* Exercise lbg_ex09

## lbgfs2024 0.11.2

* Corrected link to ohp_l07

## lbgfs2024 0.11.1

* Solution lbg_ex07

## lbgfs2024 0.11.0

* OHP_L08

# Week 10 
## lbgfs2024 0.10.4

* Exercise lbg_ex08

## lbgfs2024 0.10.3

* Slides l10

## lbgfs2024 0.10.2

* Slides l09

## lbgfs2024 0.10.1

* Course notes chapter 6

## lbgfs2024 0.10.0

* OHP-L07

# Week 9 
## lbgfs2024 0.9.3

* Exercise lbg_ex07

## lbgfs2024 0.9.2

* Solutions lbg_06

## lbgfs2024 0.9.1

* Solutions lbg_05
* Solutions lbg_04

## lbgfs2024 0.9.0

* OHP-L06

# Week 8 
## lbgfs2024 0.8.3

* Slides l07_num_rel_mat

## lbgfs2024 0.8.2

* Exercise lbg_ex06

## lbgfs2024 0.8.1

* Course Notes 05_gencov

## lbgfs2024 0.8.0

* OHP-L05

# Week 7 
## lbgfs2024 0.7.3

Material for week 7:

* [Adapted Course notes 04_blup](https://charlotte-ngs.github.io/lbgfs2024/course_notes/04_blup.pdf)
* [Course Notes Appendix 4.6](https://charlotte-ngs.github.io/lbgfs2024/course_notes/046_blup_deriv_app.pdf)
* [Adapted slides l05_blup](https://charlotte-ngs.github.io/lbgfs2024/slides/l05_blup.pdf)
* [Exercise lbg_ex05](https://charlotte-ngs.github.io/lbgfs2024/exercises/lbg_ex05/lbg_ex05.html)


## lbgfs2024 0.7.2

* Exercise lbg_ex05

## lbgfs2024 0.7.1

* Adapted chapter 04 of cn
* Added appendix 4.6 to cn

## lbgfs2024 0.7.0

* Zoom-video of lecture
* Slides with annotations

# Week 6 
## lbgfs2024 0.6.5

Material for week 6:

* [Course notes 04_blup](https://charlotte-ngs.github.io/lbgfs2024/course_notes/04_blup.pdf)
* [Exercise lbg_ex04](https://charlotte-ngs.github.io/lbgfs2024/exercises/lbg_ex04/lbg_ex04.html)
* [Slides l05_blup](https://charlotte-ngs.github.io/lbgfs2024/slides/l05_blup.pdf)

## lbgfs2024 0.6.4

* Exercise lbg_ex04

## lbgfs2024 0.6.3

* Slides l06

## lbgfs2024 0.6.2

* Course notes cn_04-blup

## lbgfs2024 0.6.1

* Slides l05

## lbgfs2024 0.6.0

* Zoom-link

# Week 5 
## lbgfs2024 0.5.4

* Slides l04

## lbgfs2024 0.5.3

* Solutions lbg_sol03

## lbgfs2024 0.5.2

* Appendix 3: Computing with Variances

## lbgfs2024 0.5.1

* Solutions lbg_sol02

## lbgfs2024 0.5.0

* OHP l04

# Week 4 
## lbgfs2024 0.4.3

Material for week 4:

* [Exercise lbg_ex03](https://charlotte-ngs.github.io/lbgfs2024/exercises/lbg_ex03/lbg_ex03.html)
* [Slides sl_l03](https://charlotte-ngs.github.io/lbgfs2024/slides/l03_qg_multiple_loci.pdf)
* [OHP ohp_l03](https://drive.google.com/file/d/1TP2xgk0tPzpcmIFZeY2ft4Oud5Yqy3cL/view)

## lbgfs2024 0.4.2

* Exercise lbg_ex03

## lbgfs2024 0.4.1

* Slides sl_l03

## lbgfs2024 0.4.0

* OHP l03

# Week 3 
## lbgfs2024 0.3.3

Material for week 3:

* [Exercise lbg_ex02](https://charlotte-ngs.github.io/lbgfs2024/exercises/lbg_ex02/lbg_ex02.html)
* [OHP l02](https://drive.google.com/file/d/12eV76mtz5nKxTJ1dvbfrq7vNb18D69Kf/view?usp=sharing)

## lbgfs2024 0.3.2

* Exercise lbg_ex02

## lbgfs2024 0.3.1

* OHP l02

## lbgfs2024 0.3.0

* First version of solutions lbg_sol01
* Re-designed exercise and solutions qmd documents

# Week 2 
## lbgfs2024 0.2.4

Links to available material for week 2: 

* Exercise [Genotype Data](https://charlotte-ngs.github.io/lbgfs2024/exercises/lbg_ex01/lbg_ex01.html)
* Overhead Pictures: [Introduction](https://charlotte-ngs.github.io/lbgfs2024/ohp/20240920_ohp_l01.pdf)


## lbgfs2024 0.2.3

* Started exercise 

## lbgfs2024 0.2.2

* Outsource pdf-result of ohp document

## lbgfs2024 0.2.1

* First version of ohp document

## lbgfs2024 0.2.0

* Started overhead pictures

# Week 1 
## lbgfs2024 0.1.7

Links to available material for week 1: 

* Course Notes: [Introduction](https://charlotte-ngs.github.io/lbgfs2024/course_notes/01_intro.pdf)
* Course Notes: [Basics of Quantitative Genetics](https://charlotte-ngs.github.io/lbgfs2024/course_notes/02_basic_qg.pdf)
* Appendix: [Linear Algebra](https://charlotte-ngs.github.io/lbgfs2024/course_notes/A1_lin_alg.pdf)
* Slides l01: [Introduction](https://charlotte-ngs.github.io/lbgfs2024/slides/l01_intro_lbg.pdf)
* Slides l02: [Basics of Quantitative Genetics](https://charlotte-ngs.github.io/lbgfs2024/slides/l02_basics_qg.pdf)

## lbgfs2024 0.1.6

* Topics for MSC and internships

## lbgfs2024 0.1.5

* Added slides for l02

## lbgfs2024 0.1.4

* Stepwise migration of slides

## lbgfs2024 0.1.3

* Start preparation of slides l01_intro

## lbgfs2024 0.1.2

* Link to moodle page

## lbgfs2024 0.1.1

Adding links to the material of week 1

* Course Notes: [Introduction](https://charlotte-ngs.github.io/lbgfs2024/course_notes/01_intro.pdf)
* Course Notes: [Basics of Quantitative Genetics](https://charlotte-ngs.github.io/lbgfs2024/course_notes/02_basic_qg.pdf)
* Appendix: [Linear Algebra](https://charlotte-ngs.github.io/lbgfs2024/course_notes/A1_lin_alg.pdf)

## lbgfs2024 0.1.0

* First release of website for week 1

# Week 0 
## lbgfs2024 0.0.9

## lbgfs2024 0.0.8

* Started deployment to Github pages

## lbgfs2024 0.0.7

* Added stub-pages for exercises and solutions

## lbgfs2024 0.0.6

* Modified structure of weekly news

## lbgfs2024 0.0.5

* Refactored quarto render script for the website to make it possible to be called from any directory in the main course repo

## lbgfs2024 0.0.4

* Implemented new package structure

## lbgfs2024 0.0.3

* Added about page

## lbgfs2024 0.0.2

* Start to add weekly news

## lbgfs2024 0.0.1

* Initial draft version of lecture material.

---

 _Latest Changes: 2024-12-01 09:01:57 CET (pvr)_