---
title: "Slides"
---

```{r}
#| echo: false
s_slides_url <- "https://charlotte-ngs.github.io/lbgfs2024/slides/"
```

List of slides documents

```{r}
#| echo: false
#| message: false
#| warning: false
s_sl_path <- "slides.dat"
tbl_sl <- readr::read_delim(file = s_sl_path, delim = ";")
tbl_sl$Nr <- 1:nrow(tbl_sl)
# create topic from text and filename
tbl_sl <- dplyr::mutate(tbl_sl, Topic = paste0("[", Text, "](", s_slides_url, Filename,")"))
# select relevant columns
tbl_sl <- dplyr::select(tbl_sl,Nr,Date,Topic)
# show knitr
knitr::kable(tbl_sl)
```

Slides with annotations

```{r}
#| echo: false
#| message: false
#| warning: false
s_swa_path <- "slides_with_annotation.dat"
tbl_swa <- readr::read_delim(file = s_swa_path, delim = ";")
tbl_swa$Nr <- 1:nrow(tbl_swa)
# create topic from text and filename
tbl_swa <- dplyr::mutate(tbl_swa, Topic = paste0("[", Text, "](", Filename,")"))
# select relevant columns
tbl_swa <- dplyr::select(tbl_swa,Nr,Date,Topic)
# show knitr
knitr::kable(tbl_swa)
```


```{r}
#| echo: false
#| results: asis
if (is.element("rmdhelp", installed.packages()))
  cat(paste0(rmdhelp::get_latest_change()))
```

